export const SPACING = <const>{
  PAGE_PADDING_TOP: 24,
  PAGE_PADDING_LEFT: 46,
  PAGE_PADDING_RIGHT: 46,
  PAGE_PADDING_BOTTOM: 24,
  BACKGROUND_IMAGE_GUTTER_X: 36,
  BACKGROUND_IMAGE_GUTTER_Y: 34,
};
